### ISSUE TITLE
我的爬虫跑了两天以后突然报了一个错误ResponseError: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by whwq2012** [ioiogoo/scrapy-monitor#3]
请问下可能是redis的问题吗？

2017-01-21 14:50:36 [scrapy.core.scraper] ERROR: Error downloading <GET http://taocan.ctrip.com/sh/316231.html>
Traceback (most recent call last):
  File "/home/whwq2012/xiecheng/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/whwq2012/xiecheng/venv/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/home/whwq2012/xiecheng/xiecheng/monitor/statscol.py", line 22, in process_request
    self.formatStats(spider.crawler.stats.get_stats())
  File "/home/whwq2012/xiecheng/xiecheng/monitor/statscol.py", line 29, in formatStats
    self.insert2redis(key, value)
  File "/home/whwq2012/xiecheng/xiecheng/monitor/statscol.py", line 32, in insert2redis
    self.r.rpush(key, value)
  File "/home/whwq2012/xiecheng/venv/lib/python2.7/site-packages/redis/client.py", line 1282, in rpush
    return self.execute_command('RPUSH', name, *values)
  File "/home/whwq2012/xiecheng/venv/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/whwq2012/xiecheng/venv/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/whwq2012/xiecheng/venv/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: NOAUTH Authentication required.

**Comment by ioiogoo** [comment]
http://serverfault.com/questions/722803/redis-error-noauth-authentication-required
没有授权验证
