### ISSUE TITLE
请问怎么解决requests访问5000端口时，“目标计算机积极拒绝，无法连接”的问题？

### ISSUE THREAD

**Issue by MarkShawn2020** [ioiogoo/scrapy-monitor#5]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\MyProjects\GitProjects\scrapy-monitor\visiter\visiter\monitor\statscol.py", line 42, in close_spider
    requests.get('http://127.0.0.1:5000/signal?sign=closed')
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /signal?sign=closed (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017339073908>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by ioiogoo** [comment]
检查5000端口是否开启
你是否开启了monitor.app的web项目？
